### ISSUE TITLE
demo_api container isnt running. I am trying to build all using dockercompose

### ISSUE THREAD

**Issue by wiqram** [Joker666/microservice-demo#3]
Error is below. Can you please help? Am I missing something? I have tried to search around on the net but not yet able to pinpoint exactly what the issue could be

Recreating 8ac9bb67ae84_microservice-demo_api_1 ... error

ERROR: for 8ac9bb67ae84_microservice-demo_api_1  Cannot start service api: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"apiService\": executable file not found in $PATH": unknown

ERROR: for api  Cannot start service api: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"apiService\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by Joker666** [comment]
This could be related to taskService, but to be able to pinpoint your exact situation, could you comment out building task in docker-compose.yml and run?

You would also need to comment out task in https://github.com/Joker666/microservice-demo/blob/main/docker-compose.yml#L62

Let me know if that worked

**Comment by Joker666** [comment]
Could you first confirm, all the other services are running properly?

Golang builds it's binary and places it in $GOPATH/bin when it executes the build script in here, https://github.com/Joker666/microservice-demo/blob/main/apiService/build.sh

The error essentially states that it does not find `apiService` binary to execute on the path. First, make sure that the binary is being created successfully. And then if the binary exists on the path.

To debug, try building the dockerfile inside apiService and run it. Try modifying the `ENTRYPOINT` in the dockerfile to point to the `apiService` binary

**Comment by wiqram** [comment]
Doesn’t work. Same error.

It only happens using docker compose but When I try to use docker build command on apiservice specifically, that module builds fine.

The issue is in L26 of Dockerfle of apiService –
ENTRYPOINT ["apiService"]

It breaks here. And it could be because I am running this on windows 10 if it has anything to do with shellscript. I have had to fix another shell script issue by specially converting a .sh file using a dos2unix command in the dockerfile. Here is what I did for build.sh in apiservice dockerfile –


RUN apt-get update && apt-get install -y dos2unix

COPY /build.sh /buildNew.sh

#RUN dos2unix /buildNew.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*
# Build App
RUN dos2unix /buildNew.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

If the entrypoint does in turn do a shell script then I may have to find another way which is windows friendly to do the same.

Below is the same issue after removing the taskservice from docker-compose

[cid:image002.png@01D6BF1A.96D73730]

**Comment by wiqram** [comment]
Just sent you a response to your other suggestion. I can confirm that other services are running properly except the apiservice.

As noted in my previous email I too suspect the issue is on the entrypoint command itself. If the executable binary is in gopath/bin then let me check if it does exist there in that specific image.

If it does, then at the risk of asking you a daft question, what would be a command change to Entrypoint to make it work?

**Comment by wiqram** [comment]
I replaced with entrypoint command with below change to dockerfile in apiservice –
CMD ["$GOPATH/bin","apiService"]

And I have a different thing this time that docker did not find -

Recreating fe3228fab900_microservice-demo_api_1 ... error

ERROR: for fe3228fab900_microservice-demo_api_1  Cannot start service api: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"serve\": executable file not found in $PATH": unknown

ERROR: for api  Cannot start service api: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"serve\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.

Also, when I inspect the docker image, I see this structure which is what you would expect –
[cid:image001.png@01D6BF2F.C2F71870]

Is it something related to the mounting of the image at the right location to find the executable? Also what is the purpose of “apiService” as an entrypoint? Could we replace it with run.sh instead?

Thank you for your time on this though. Much appreciated.

From: vikram bharwani
Sent: 20 November 2020 09:05
To: Joker666/microservice-demo <reply@reply.github.com>; Joker666/microservice-demo <microservice-demo@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Joker666/microservice-demo] demo_api container isnt running. I am trying to build all using dockercompose (#3)

Just sent you a response to your other suggestion. I can confirm that other services are running properly except the apiservice.

As noted in my previous email I too suspect the issue is on the entrypoint command itself. If the executable binary is in gopath/bin then let me check if it does exist there in that specific image.

If it does, then at the risk of asking you a daft question, what would be a command change to Entrypoint to make it work?

**Comment by Joker666** [comment]
I see the second error is almost similar to the first error and I am able to recreate it if I put a wrong path for `apiService` in ENTRYPOINT.
You do not need a command change in ENTRYPOINT to make it work, you just need to find where the binary is and point the path to it in here. I do not have access to a windows machine, only tested in Unix based environments.
Since the docker build works on `apiService`, comment out connecting to other services in `cmd/serve` file and run the docker build with `docker run`. Then exec into the container to find where the binary is located.

Why won't run.sh work? Because it essentially builds the build script and runs it from $GOPATH with `serve` flag which starts the Golang server. But since all the other services are not ready, it won't be able to connect to these services. So we need to start the Golang server after all the services are up and running.

**Comment by wiqram** [comment]
Thank you Hasan. I will follow the steps as instructed. Much appreciated in you spending this time on this.

________________________________

**Comment by wiqram** [comment]
Hasan, I did what you asked me to earlier and while browsing the docker image of apiservice it clicked me the issue with this. So your code works out of the box if its run on unix but if it is run on windows then we have to do the transform of .sh files from dos to unix because of the wonkly /nl issues on every line in .sh file.

For that I added this to dockerfile of apiservice –

RUN apt-get update && apt-get install -y dos2unix

COPY /build.sh /buildNew.sh

RUN dos2unix buildNew.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

And it copied the buildNew on the root folder and hence when running entrypoint it has the buildNew on root where obviously the apiService wont be recognised.

So for your windows users you may want to maybe add the below entry in dockerfile of apiservice which works –


RUN apt-get update && apt-get install -y dos2unix

COPY /build.sh ${SRC_DIR}/buildNew.sh

RUN dos2unix ${SRC_DIR}/buildNew.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*




I have run docker build specifically for apiService and browsed the file system. This is what it comes back with –


[cid:image001.png@01D6BF5D.DDD5AC00]

And apiService is under go/bin/ as you specified in your email

[cid:image002.png@01D6BF5E.3D4A0320]

Cd

**Comment by Joker666** [comment]
Great that it worked out for you!
