### ISSUE TITLE
Data in the databases

### ISSUE THREAD

**Issue by wiqram** [Joker666/microservice-demo#4]
Hello Ahad, great effort with this one. Thanks for this.

Can you please confirm what scripts you have used to update the data in the databases (postgre, MySQL and mongo)? I am able to run this but the localhost:9090 doesn't give must output other than a json style output with 1 record...

Also, I understand that this may not be an issue and It may be working as designed and I may have to update the data but be good if you can just confirm how I can make some data available to allow me to see the output on the screen...

**Comment by Joker666** [comment]
Hi Wiqram,

First of all, there is no seed data here for you to check. I plan to add some, also plan to add a frontend microservice to visualize the project.

So the purpose of this project is to show how different services can connect to each other and how an API gateway can serve as a proxy to connect to these services. The data is not the important part but serves to show a real work example. You can go to swagger ui by, http://localhost:9090/swagger-ui and see the routes. First you would need to register a user and use the auth token to create project or task

**Comment by wiqram** [comment]
Thanks Hasan for the quick response.
